### ISSUE TITLE
Error installing manually

### ISSUE THREAD

**Issue by okitupadmin** [kuun/xdebug-trace-viewer#1]
Maybe I'm doing something wrong, but I can't install the software.
Can you help me?
Thanks in advance.

My npm version is: 6.9.0 and i'm running it as root

Here i put the command that I executed:

-----------------------------------------------------

cd /tmp
git clone https://github.com/kuun/xdebug-trace-viewer.git
cd /tmp/xdebug-trace-viewer
npm install gulp-cli -g
   /usr/bin/gulp -> /usr/lib/node_modules/gulp-cli/bin/gulp.js
   + gulp-cli@2.2.0
   updated 1 package in 7.303s

root@test:/tmp/xdebug-trace-viewer# npm install

> core-js@2.6.9 postinstall /tmp/xdebug-trace-viewer/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> electron@5.0.9 postinstall /tmp/xdebug-trace-viewer/node_modules/electron
> node install.js

/tmp/xdebug-trace-viewer/node_modules/electron/install.js:49
  throw err
  ^

Error: EACCES: permission denied, mkdir '/tmp/xdebug-trace-viewer/node_modules/electron/.electron'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@5.0.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@5.0.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-02T10_36_02_291Z-debug.log

**Comment by kuun** [comment]
> Error: EACCES: permission denied, mkdir '/tmp/xdebug-trace-viewer/node_modules/electron/.electron

maybe you don't have permession to create directory '/tmp/xdebug-trace-viewer/node_modules/electron/.electron',

**Comment by kuun** [comment]
please try newer version nodejs

**Comment by kuun** [comment]
If you run npm with root, please try:
```
npm install --unsafe-perm=true --allow-root
```

**Comment by okitupadmin** [comment]
Finally it works!
My final recipe to install was as standard user (non root):
`cd /tmp`
`git clone https://github.com/kuun/xdebug-trace-viewer.git`
`cd /tmp/xdebug-trace-viewer/`
`sudo npm install gulp-cli -g`
`npm install`
`npm run ejs`
`npm start`

The difference with the README recipe is that I need to prepare with sudo: "**sudo npm install gulp-cli -g**", otherwise I have reports as: Error: EACCES: permission denied, access '/usr/lib/node_modules/gulp-cli'

Thanks so much for your time! ;)
