### ISSUE TITLE
MacOS build: image /Users/***/Projects/xdebug-trace-viewer/build/icon.png must be at least 512x512

### ISSUE THREAD

**Issue by renepardon** [kuun/xdebug-trace-viewer#2]
Hello,
first at all, nice job! Screenshots look nice.

If you build on Mac OS you need the Icon image with at least 512px X 512px. If you change this, the build works as expected.

I'm btw not able to open/load a trace file because on Mac I have no related menu item to do so.

**Comment by kuun** [comment]
Sorry, I don't have Mac OS, please help me test it and open a pull request

**Comment by berliner** [comment]
Should have been fixed now by https://github.com/kuun/xdebug-trace-viewer/pull/9#event-3810835858
